version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

goos: linux

goarch: amd64

main: ./cmd/node-exporter-lite/main.go

ldflags:
  - "-s"
  - "-w"

binary: node-exporter-lite-{{ .Os }}-{{ .Arch }}