name: Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      matrix:
        os:
          - linux
          # - openbsd
          # - freebsd
        arch:
          - amd64
          - arm64
          - arm
          - armv7
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: 1.22
      config-file: .github/release/release.${{matrix.os}}.${{matrix.arch}}.yml
      

