name: Go releaser
on:
  workflow_run:
    workflows: [Dynamic Template]
    types:
      - completed

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      matrix:
        os:
          - linux
          - openbsd
          - freebsd
        arch:
          - amd64
          - arm64
          - armv7
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: 1.23
      config-file: .github/release/release.${{matrix.os}}.${{matrix.arch}}.yml
      

